@extends('new_website.layouts.main')

@section('content')
    <div class="container text-white" style="padding-top:120px">
        <h2 style="text-align:center;">Privacy Policy</h2>
        1. Age Requirement<br>
        • Participants must be at least 21 years of age to play Square Jungle.<br>
        2. No Overtime/Tie Breakers<br>
        • The game follows a policy of no overtime or tie-breakers. Results are based on the
        official game quarters.<br>
        3. Honor System Agreement<br>
        • Square Jungle operates on an honor system. By participating, players commit to the
        game's rules and regulations.<br>
        4. Board Selection and Commitment<br>
        • Players choose two categories and commit to playing both boards.<br>
        • Once a square is selected, it is locked under the player's Alias. No changes are allowed
        after selection.<br>
        5. Payment Guidelines<br>
        • Payment is only required when the entire board is filled.<br>
        • In the event the board is not filled by the deadline, the game is closed, and no payment
        is required from participants.<br>
        6. Admin Rights<br>
        • The administrator reserves the right to determine the number of boards and games to
        be played.<br>
        7. Weekly Picks<br>
        • Players are responsible for making their weekly picks on time.<br>
        • Missed deadlines for picks may result in the board not being re-opened, except in
        specific circumstances as announced by the administrator.<br>
        8. Payment Delinquency<br>
        • Players are expected to make payments during the open period.<br>
        • If a player's name is removed three times from squares due to non-payment after the
        deadline, the player will be locked out and removed from the website.<br>
        <h2>Game Rules</h2>
        1. Board Descriptions<br>
        • A 10x10_4 board consists of 100 squares with four quarters, each having a new number
        generated by default.<br>
        • A 10x10_1 board consists of 100 squares with one set of generated numbers for all four
        quarters, subject to participant votes.<br>
        2. Square Selection<br>
        • Boards consist of 10 columns and 10 rows, totaling 100 squares.<br>
        • A 10x10_4 board has 4 rows and 4 columns, numbered from 0 to 9.<br>
        • A 10x10_1 board has 1 row and 1 column, numbered from 0 to 9.<br>
        • Players can purchase as many squares as they wish, with this subject to participant
        votes.<br>
        3. Determining Winners<br>
        • At the end of each quarter, the winning square corresponds to the intersection of the
        row and column with matching numbers.<br>
        4. Prize Payout<br>
        • Prize payouts will occur after the game and will be posted online.<br>
        By participating in Square Jungle, you acknowledge and agree to abide by these rules and the
        privacy policy outlined herein.
        <h3>Privacy Policy Statement</h3>
        We hold your information with the utmost privacy and will never sell or
        give your information to third parties.<br>
        Your football pool is kept private this site requires all of your football
        pool participants to log in so no unauthorized users cannot get into your
        football pool and look at your data.<br>
        Our website is https compliance website security is extremely important,
        no matter the types of information businesses are saving or transmitting.<br>
        Setting up encryption and authentication for your website can mean the
        difference between providing a secure site for users versus potentially leaking sensitive
        data.<br>
        HTTPS has the additional SSL/TLS layer to ensure all data being transferred is
        encrypted and secure.<br>
        The security provided by HTTPS is essential for sites that send sensitive
        information, such as credit card information or billing addresses and people's names and
        email addresses.<br>
    </div>
@endsection
