<link rel="icon" type="image/x-icon" href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,900;1,800;1,900&family=Noto+Naskh+Arabic&family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,700;1,200;1,300&display=swap"
    rel="stylesheet">
<link type="text/css" rel="stylesheet" href="../css/image-uploader.min.css">
<link rel="stylesheet" href="{{ asset('assets/admin/css/style.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('assets/admin/css/main.css') }}" type="text/css">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">

<style type="text/css">
    #cover {
        position: absolute;
        top: 50%;
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
        background: #ffffff;
        z-index: 9999;
        font-size: 65px;
        text-align: center;
        padding-top: 400px;
        color: #000000;
        font-family: tahoma;
    }

    @keyframes ldio-gnrzupa2le8 {
      0% { transform: translate(-50%,-50%) rotate(0deg); }
      100% { transform: translate(-50%,-50%) rotate(360deg); }
    }
    .ldio-gnrzupa2le8 div {
      position: absolute;
      width: 81.3px;
      height: 81.3px;
      border: 5.42px solid #500e60;
      border-top-color: transparent;
      border-radius: 50%;
    }
    .ldio-gnrzupa2le8 div {
      animation: ldio-gnrzupa2le8 1.8518518518518516s linear infinite;
      top: 135.5px;
      left: 135.5px
    }
    .loadingio-spinner-rolling-avt82ldo9vj {
      width: 271px;
      height: 271px;
      display: inline-block;
      overflow: hidden;
      background: transparent;
    }
    .ldio-gnrzupa2le8 {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-gnrzupa2le8 div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>




